sudo: required
services:
- docker
before_install:
- docker build -t josemelendezbolanos21/heroku-test -f ./client/Dockerfile.dev ./client
script:
- docker run josemelendezbolanos21/heroku-test npm run test -- --coverage
after_success:
- docker build -t josemelendezbolanos21/heroku-client ./client
- docker build -t josemelendezbolanos21/heroku-server ./server
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
- docker push josemelendezbolanos21/heroku-client
- docker push josemelendezbolanos21/heroku-server
deploy:
  provider: heroku
  api_key:
    secure: b0zI52sVUcr1Efyf2UzhoqR5QvY5O8CviphTXTNM8MM35hR+NltIuDibpMut12OmPJMio+DPE0kUv0niSFAR4MT1yVr5UMv5fZQ335PIWzpbsAufaojWoa0Gm1BhD03pCDNTTXAWCwUCKi9BqOlfAqgiqciqHJCcOv+qMsZDfo6Z2OxhN1jfTAvV6ZPsI+Opzh+XMCHmGvpxOEe21CZJuS7CW4dxRcpWViMbpZ+gENcYQ/3FloMEwsYC31RQoTsDNjaHo+G5UXP91j83jLb97Luk04u2GM4GXXe70sX5xbePqHl/BP+xSjv/j702YLnCGoM0yY6w30YfNMMvTuO6rLow7rQdnNYYNO2X6m5SzVHXhaAirXn7R3d9/Sx21lqk/J+IuYG/0XBxL6twsjjYtma6Kj/RIGxyS4oQf5U9gLaI4W7gzwgr0VJ0Y70AkkJLhMV+UNQJueUnOopZNNQWXrXqRIapjSmCXMcCvHZuiXawFtrjnfKgVPKcP0xeA/iUMtTY5JmciuYcQQMlLK3qnBCOAZtkNvQhHUsbRS25vOZdkdi093vdvm1qIjYWlBXxYTS0p+KNSM3XvoVLvjNV0YWe8Z2/OQiYk83JN5EArHO1vXkbuE9oMK/JbjalsatWtxPecCk5V7ZiAEG231Im36gP5o9CRHNTqzMASc/IFYw=
  app: intense-gorge-24369
