sudo: required
services:
- docker
before_install:
- docker build -t josemelendezbolanos21/heroku-test -f ./client/Dockerfile.dev ./client
script:
- docker run josemelendezbolanos21/heroku-test npm run test -- --coverage
after_success:
- docker build -t josemelendezbolanos21/heroku-client ./client
- docker build -t josemelendezbolanos21/heroku-server ./server
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
- docker push josemelendezbolanos21/heroku-client
- docker push josemelendezbolanos21/heroku-server
deploy:
  provider: heroku
  api_key:
    secure: P7XqrRsuygw7PBALui6/Q80Ou5ziSky8Wc2ukEjhC2FsTDH0Qn8wJvz9YuCbWFWh+2CccUNXXh0AtqmwcTY9Kbp7kfWbd+kojo680g19Ki+4nZCrVBZh91O+BKQR06SmD2yQvdtYqWD45wuxMZ613ZNTF/EUx3m/V429g/BsGlFEMjqGU/FgOiDVWgHY3flBbgK2V4yEY+Ycq93ZhdTHcGbj6jKxymE+slhSkzsRcSABcVOdryjstmL0FogPZMZAUzLxKM92npAmrH7WXROAoPQLqUrQQrmztODblHuPQFw4C3wLkxE8FDaXfO4kqikDsOoF70WdF3ZFgOyuCG9UDyz8hnUrcmAuwD8Gq0YckU9D+FS1Z49fC2+PnCDs5xDOlN+brEVFsGn37cWJzue+PvZIdFrDC5nbXI5bmklofZZNRfh0js85T/8njW83/h6BSBtozH7Y77jDhQzgxFVSyAfvHbtrQ3EN8JQLURUanWQxyCr/eu1G0e1qHvpyNTOSVE9D1j61EzSJpkF093aFBfMvZYVeLbzen58kD//Kl0IE0goczD6Kf7o+ZkunL6M7wk5d8oXQWnqovtSxsK7022LXMxka7hZI1A2D7Oxc312dUeTiBLj9uBxXYh39Vyj8hC/dfPtyrfYwdOp9j/9wOFv7stAsJlojVIGEGGbLcAs=
  app: intense-gorge-24369